alias la='ls -lahFG'

## git

alias ga='git add'
alias ga\.='git add .'
alias gbD='git branch -D'
alias gba='git branch --all'
alias gbd='git branch -d'
alias gch='git checkout'
alias gcom='git commit -m'
alias gd='git diff'
alias gdfl='git diff HEAD~1'
alias gds='git diff --staged'
alias gl='git log --stat --oneline'
alias gpull='git pull'
alias gpush='git push'
alias gs='git status -s'
alias gst='git stash'
alias gstp='git stash pop'
alias gunadd='git reset'
alias gunchange='git checkout HEAD --'
